# Copyright Microsoft Corporation
# This Sample Code is provided for the purpose of illustration only and is not intended to be used in a production environment.
# THIS SAMPLE CODE AND ANY RELATED INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE. 
# We grant You a nonexclusive, royalty-free right to use and modify the Sample Code and to reproduce and distribute the object code form of the Sample Code, provided that You agree:
# (i) to not use Our name, logo, or trademarks to market Your software product in which the Sample Code is embedded;
# (ii) to include a valid copyright notice on Your software product in which the Sample Code is embedded; and
# (iii) to indemnify, hold harmless, and defend Us and Our suppliers from and against any claims or lawsuits, including attorneysâ€™ fees, that arise or result from the use or distribution of the Sample Code.
# Please note: None of the conditions outlined in the disclaimer above will supersede the terms and conditions contained within the Premier Customer Services Description.

name: Pack Solution with Actions

on:
  workflow_dispatch:
    inputs:
      solution-name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default:  'ContosoAPI'
      branch-type:
        required: false
        type: choice
        options:
        - feature
        - hotfix
        - development
        - main
        default:
          feature
      branch-name:
        description: 'name of the git branch'
        required: false
        default:  '001'



jobs:
  setup:
    environment: ${{ inputs.source-environment }}
    permissions:
      actions: read
      repository-projects: write
      contents: write
    runs-on: ubuntu-latest
    steps:    
    - env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: |
        echo $EVENT_CONTEXT
    - name: Variables      
      run: |        
        echo "Solution Name :'contoso_university_core'"        
        echo "ref ${{ github.ref }}"        
        echo "GITHUB_REF ${{ github.GITHUB_REF }}"   
    - name: Debug output
      shell: pwsh
      run: |
        Get-ChildItem  -Recurse | foreach { write-host $_.FullName }
  pack:
    needs: [setup]
    uses: Contoso-W-Enterprise/PowerPlatformALM/.github/workflows/workflow-pack-solution.yml@main
    with: 
      solution-name: '${{ inputs.solution-name }}'
      branch-type: '${{ inputs.branch-type }}'
      branch-name: '${{ inputs.branch-name}}'
